<a href="https://colab.research.google.com/github/ayushhh026/RuppeRisk/blob/main/notebooks/Model04_Bureau_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np

Mounted at /content/drive

In [2]:
DATA_PATH = "/content/drive/MyDrive/datasets/raw/"

In [4]:
bureau = pd.read_csv(DATA_PATH + "bureau.csv")

print("Bureau shape:", bureau.shape)
display(bureau.head())

Bureau shape: (1716428, 17)

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [5]:
bureau.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1716428 entries, 0 to 1716427
Data columns (total 17 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_CURR              int64
 1   SK_ID_BUREAU            int64
 2   CREDIT_ACTIVE           object
 3   CREDIT_CURRENCY         object
 4   DAYS_CREDIT             int64
 5   CREDIT_DAY_OVERDUE      int64
 6   DAYS_CREDIT_ENDDATE     float64
 7   DAYS_ENDDATE_FACT       float64
 8   AMT_CREDIT_MAX_OVERDUE  float64
 9   CNT_CREDIT_PROLONG      int64
 10  AMT_CREDIT_SUM          float64
 11  AMT_CREDIT_SUM_DEBT     float64
 12  AMT_CREDIT_SUM_LIMIT    float64
 13  AMT_CREDIT_SUM_OVERDUE  float64
 14  CREDIT_TYPE             object
 15  DAYS_CREDIT_UPDATE      int64
 16  AMT_ANNUITY             float64
dtypes: float64(8), int64(6), object(3)
memory usage: 222.6+ MB

In [6]:
print("Number of columns:", len(bureau.columns))
print("\nColumns:")
for col in bureau.columns:
    print("-", col)

Number of columns: 17

Columns:
- SK_ID_CURR
- SK_ID_BUREAU
- CREDIT_ACTIVE
- CREDIT_CURRENCY
- DAYS_CREDIT
- CREDIT_DAY_OVERDUE
- DAYS_CREDIT_ENDDATE
- DAYS_ENDDATE_FACT
- AMT_CREDIT_MAX_OVERDUE
- CNT_CREDIT_PROLONG
- AMT_CREDIT_SUM
- AMT_CREDIT_SUM_DEBT
- AMT_CREDIT_SUM_LIMIT
- AMT_CREDIT_SUM_OVERDUE
- CREDIT_TYPE
- DAYS_CREDIT_UPDATE
- AMT_ANNUITY

In [7]:
print("Data type distribution:")
display(bureau.dtypes.value_counts())

Data type distribution:

float64    8
int64      6
object     3
Name: count, dtype: int64

In [8]:
print("Duplicate rows:", bureau.duplicated().sum())

Duplicate rows: 0

In [9]:
print("Total rows:", len(bureau))
print("Unique SK_ID_CURR:", bureau["SK_ID_CURR"].nunique())
print("Unique SK_ID_BUREAU:", bureau["SK_ID_BUREAU"].nunique())

Total rows: 1716428
Unique SK_ID_CURR: 305811
Unique SK_ID_BUREAU: 1716428

In [10]:
print("SK_ID_CURR represents the applicant.")
print("SK_ID_BUREAU represents an individual bureau credit record.")
print("Rows per applicant:")

credits_per_customer = bureau.groupby("SK_ID_CURR").size()
display(credits_per_customer.describe())

SK_ID_CURR represents the applicant.
SK_ID_BUREAU represents an individual bureau credit record.
Rows per applicant:

count    305811.000000
mean          5.612709
std           4.430354
min           1.000000
25%           2.000000
50%           4.000000
75%           8.000000
max         116.000000
dtype: float64

In [11]:
print("Number of applicants with each bureau-history count:")
display(credits_per_customer.value_counts().sort_index().head(30))

Number of applicants with each bureau-history count:

1     41520
2     41004
3     37828
4     33467
5     28913
6     24329
7     20095
8     16736
9     13073
10    10518
11     8456
12     6564
13     5144
14     4129
15     3061
16     2394
17     1969
18     1513
19     1133
20      886
21      682
22      545
23      381
24      304
25      217
26      200
27      142
28      135
29       88
30       56
Name: count, dtype: int64

In [12]:
app_train_ids = pd.read_csv(DATA_PATH + "application_train.csv", usecols=["SK_ID_CURR"])

bureau_ids = set(bureau["SK_ID_CURR"].unique())
application_ids = set(app_train_ids["SK_ID_CURR"])
ids_without_bureau = application_ids - bureau_ids

print("Applicants with NO bureau history:", len(ids_without_bureau))
print("Percentage:", f"{len(ids_without_bureau) / len(app_train_ids) * 100:.2f}%")

Applicants with NO bureau history: 44020
Percentage: 14.31%

In [13]:
missing_summary = pd.DataFrame({
    "Missing_Count": bureau.isna().sum(),
    "Missing_Percentage": bureau.isna().mean() * 100
})

missing_summary = missing_summary.sort_values("Missing_Percentage", ascending=False)

print("Missing-value summary:")
display(missing_summary)

Missing-value summary:

                        Missing_Count  Missing_Percentage
AMT_ANNUITY                   1226791           71.473490
AMT_CREDIT_MAX_OVERDUE        1124488           65.513264
DAYS_ENDDATE_FACT              633653           36.916958
AMT_CREDIT_SUM_LIMIT           591780           34.477415
AMT_CREDIT_SUM_DEBT            257669           15.011932
DAYS_CREDIT_ENDDATE            105553            6.149573
AMT_CREDIT_SUM                     13            0.000757
SK_ID_CURR                          0            0.000000
SK_ID_BUREAU                        0            0.000000
CREDIT_DAY_OVERDUE                  0            0.000000
CREDIT_ACTIVE                       0            0.000000
CREDIT_CURRENCY                     0            0.000000
DAYS_CREDIT                         0            0.000000
CNT_CREDIT_PROLONG                  0            0.000000
AMT_CREDIT_SUM_OVERDUE              0            0.000000
CREDIT_TYPE                         0            0.000000
DAYS_CREDIT_UPDATE                  0            0.000000

In [14]:
numeric_cols = bureau.select_dtypes(include=np.number).columns.tolist()

print("Number of numeric columns:", len(numeric_cols))
print("\nNumeric columns:")
for col in numeric_cols:
    print("-", col)

Number of numeric columns: 14

Numeric columns:
- SK_ID_CURR
- SK_ID_BUREAU
- DAYS_CREDIT
- CREDIT_DAY_OVERDUE
- DAYS_CREDIT_ENDDATE
- DAYS_ENDDATE_FACT
- AMT_CREDIT_MAX_OVERDUE
- CNT_CREDIT_PROLONG
- AMT_CREDIT_SUM
- AMT_CREDIT_SUM_DEBT
- AMT_CREDIT_SUM_LIMIT
- AMT_CREDIT_SUM_OVERDUE
- DAYS_CREDIT_UPDATE
- AMT_ANNUITY

In [15]:
categorical_cols = bureau.select_dtypes(include=["object"]).columns.tolist()

print("Number of categorical columns:", len(categorical_cols))
print("\nCategorical columns:")
for col in categorical_cols:
    print("-", col)

Number of categorical columns: 3

Categorical columns:
- CREDIT_ACTIVE
- CREDIT_CURRENCY
- CREDIT_TYPE

In [16]:
print("Numeric descriptive statistics:")
display(bureau[numeric_cols].describe().T)

Numeric descriptive statistics:

,count,mean,std,min,25%,50%,75%,max
SK_ID_CURR,1716428.0,2.782149e+05,1.029386e+05,100001.000,188866.75,278055.0,367426.00,4.562550e+05
SK_ID_BUREAU,1716428.0,5.924434e+06,5.322657e+05,5000000.000,5463953.75,5926303.5,6385681.25,6.843457e+06
DAYS_CREDIT,1716428.0,-1.142108e+03,7.951649e+02,-2922.000,-1666.00,-987.0,-474.00,0.000000e+00
CREDIT_DAY_OVERDUE,1716428.0,8.181666e-01,3.654443e+01,0.000,0.00,0.0,0.00,2.792000e+03
DAYS_CREDIT_ENDDATE,1610875.0,5.105174e+02,4.994220e+03,-42060.000,-1138.00,-330.0,474.00,3.119900e+04
DAYS_ENDDATE_FACT,1082775.0,-1.017437e+03,7.140106e+02,-42023.000,-1489.00,-897.0,-425.00,0.000000e+00
AMT_CREDIT_MAX_OVERDUE,591940.0,3.825418e+03,2.060316e+05,0.000,0.00,0.0,0.00,1.159872e+08
CNT_CREDIT_PROLONG,1716428.0,6.410406e-03,9.622391e-02,0.000,0.00,0.0,0.00,9.000000e+00
AMT_CREDIT_SUM,1716415.0,3.549946e+05,1.149811e+06,0.000,51300.00,125518.5,315000.00,5.850000e+08
AMT_CREDIT_SUM_DEBT,1458759.0,1.370851e+05,6.774011e+05,-4705600.320,0.00,0.0,40153.50,1.701000e+08
AMT_CREDIT_SUM_LIMIT,1124648.0,6.229515e+03,4.503203e+04,-586406.115,0.00,0.0,0.00,4.705600e+06
AMT_CREDIT_SUM_OVERDUE,1716428.0,3.791276e+01,5.937650e+03,0.000,0.00,0.0,0.00,3.756681e+06
DAYS_CREDIT_UPDATE,1716428.0,-5.937483e+02,7.207473e+02,-41947.000,-908.00,-395.0,-33.00,3.720000e+02
AMT_ANNUITY,489637.0,1.571276e+04,3.258269e+05,0.000,0.00,0.0,13500.00,1.184534e+08

In [17]:
print("Categorical value distributions:")
for col in categorical_cols:
    print("\n" + "=" * 60)
    print(col)
    print("=" * 60)
    display(bureau[col].value_counts(dropna=False).head(20))

Categorical value distributions:

============================================================
CREDIT_ACTIVE
============================================================

CREDIT_ACTIVE
Closed      1079273
Active       630607
Sold           6527
Bad debt         21
Name: count, dtype: int64

============================================================
CREDIT_CURRENCY
============================================================

CREDIT_CURRENCY
currency 1    1715020
currency 2       1224
currency 3        174
currency 4         10
Name: count, dtype: int64

============================================================
CREDIT_TYPE
============================================================

CREDIT_TYPE
Consumer credit                                 1251615
Credit card                                      402195
Car loan                                          27690
Mortgage                                          18391
Microloan                                         12413
Loan for business development                      1975
Another type of loan                               1017
Unknown type of loan                                555
Loan for working capital replenishment              469
Cash loan (non-earmarked)                            56
Real estate loan                                     27
Loan for the purchase of equipment                   19
Loan for purchase of shares (margin lending)          4
Mobile operator loan                                  1
Interbank credit                                      1
Name: count, dtype: int64

In [18]:
if "CREDIT_ACTIVE" in bureau.columns:
    print("CREDIT_ACTIVE distribution:")
    display(bureau["CREDIT_ACTIVE"].value_counts(dropna=False))

CREDIT_ACTIVE distribution:

CREDIT_ACTIVE
Closed      1079273
Active       630607
Sold           6527
Bad debt         21
Name: count, dtype: int64

In [19]:
if "CREDIT_TYPE" in bureau.columns:
    print("CREDIT_TYPE distribution:")
    display(bureau["CREDIT_TYPE"].value_counts(dropna=False).head(30))

CREDIT_TYPE distribution:

CREDIT_TYPE
Consumer credit                                 1251615
Credit card                                      402195
Car loan                                          27690
Mortgage                                          18391
Microloan                                         12413
Loan for business development                      1975
Another type of loan                               1017
Unknown type of loan                                555
Loan for working capital replenishment              469
Cash loan (non-earmarked)                            56
Real estate loan                                     27
Loan for the purchase of equipment                   19
Loan for purchase of shares (margin lending)          4
Mobile operator loan                                  1
Interbank credit                                      1
Name: count, dtype: int64

In [20]:
credit_amount_cols = [col for col in [
    "AMT_CREDIT_SUM", "AMT_CREDIT_SUM_DEBT", "AMT_CREDIT_SUM_LIMIT",
    "AMT_CREDIT_SUM_OVERDUE", "AMT_ANNUITY"
] if col in bureau.columns]

print("Credit amount columns:", credit_amount_cols)
display(bureau[credit_amount_cols].describe().T)

Credit amount columns: ['AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM_OVERDUE', 'AMT_ANNUITY']

,count,mean,std,min,25%,50%,75%,max
AMT_CREDIT_SUM,1716415.0,354994.591918,1.149811e+06,0.000,51300.0,125518.5,315000.0,5.850000e+08
AMT_CREDIT_SUM_DEBT,1458759.0,137085.119952,6.774011e+05,-4705600.320,0.0,0.0,40153.5,1.701000e+08
AMT_CREDIT_SUM_LIMIT,1124648.0,6229.514980,4.503203e+04,-586406.115,0.0,0.0,0.0,4.705600e+06
AMT_CREDIT_SUM_OVERDUE,1716428.0,37.912758,5.937650e+03,0.000,0.0,0.0,0.0,3.756681e+06
AMT_ANNUITY,489637.0,15712.757700,3.258269e+05,0.000,0.0,0.0,13500.0,1.184534e+08

In [21]:
overdue_cols = [col for col in ["AMT_CREDIT_SUM_OVERDUE", "CREDIT_DAY_OVERDUE"] if col in bureau.columns]

print("Overdue columns:", overdue_cols)
if overdue_cols:
    display(bureau[overdue_cols].describe().T)

Overdue columns: ['AMT_CREDIT_SUM_OVERDUE', 'CREDIT_DAY_OVERDUE']

,count,mean,std,min,25%,50%,75%,max
AMT_CREDIT_SUM_OVERDUE,1716428.0,37.912758,5937.650035,0.0,0.0,0.0,0.0,3756681.0
CREDIT_DAY_OVERDUE,1716428.0,0.818167,36.544428,0.0,0.0,0.0,0.0,2792.0

In [28]:
#Overdue magnitude
if "CREDIT_DAY_OVERDUE" in bureau.columns:
    print("CREDIT_DAY_OVERDUE distribution (including zeros):")
    display(bureau["CREDIT_DAY_OVERDUE"].describe())

    print("\nCREDIT_DAY_OVERDUE distribution (only overdue records):")
    display(bureau[bureau["CREDIT_DAY_OVERDUE"] > 0]["CREDIT_DAY_OVERDUE"].describe())

CREDIT_DAY_OVERDUE distribution (including zeros):

count    1.716428e+06
mean     8.181666e-01
std      3.654443e+01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.792000e+03
Name: CREDIT_DAY_OVERDUE, dtype: float64

CREDIT_DAY_OVERDUE distribution (only overdue records):

count    4217.000000
mean      333.014940
std       658.070636
min         1.000000
25%        17.000000
50%        34.000000
75%       150.000000
max      2792.000000
Name: CREDIT_DAY_OVERDUE, dtype: float64

In [29]:
#Debt information
debt_cols = [col for col in ["AMT_CREDIT_SUM", "AMT_CREDIT_SUM_DEBT", "AMT_CREDIT_SUM_LIMIT"] if col in bureau.columns]

print("Debt-related columns:", debt_cols)
display(bureau[debt_cols].describe().T)

Debt-related columns: ['AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT']

,count,mean,std,min,25%,50%,75%,max
AMT_CREDIT_SUM,1716415.0,354994.591918,1.149811e+06,0.000,51300.0,125518.5,315000.0,5.850000e+08
AMT_CREDIT_SUM_DEBT,1458759.0,137085.119952,6.774011e+05,-4705600.320,0.0,0.0,40153.5,1.701000e+08
AMT_CREDIT_SUM_LIMIT,1124648.0,6229.514980,4.503203e+04,-586406.115,0.0,0.0,0.0,4.705600e+06

In [30]:
#Debt vs credit sanity check
if "AMT_CREDIT_SUM_DEBT" in bureau.columns and "AMT_CREDIT_SUM" in bureau.columns:
    debt_exceeds_credit = (bureau["AMT_CREDIT_SUM_DEBT"] > bureau["AMT_CREDIT_SUM"]).sum()

    print(f"Records where debt exceeds total credit sum: {debt_exceeds_credit}")
    print(f"Percentage: {debt_exceeds_credit / len(bureau) * 100:.2f}%")

Records where debt exceeds total credit sum: 29642
Percentage: 1.73%

In [31]:
#Credit status per applicant
if "CREDIT_ACTIVE" in bureau.columns:
    status_per_customer = bureau.groupby("SK_ID_CURR")["CREDIT_ACTIVE"].nunique()

    print("Number of different CREDIT_ACTIVE statuses per applicant:")
    display(status_per_customer.value_counts().sort_index())

Number of different CREDIT_ACTIVE statuses per applicant:

CREDIT_ACTIVE
1     90756
2    210141
3      4912
4         2
Name: count, dtype: int64

In [32]:
#Overdue records
if "CREDIT_DAY_OVERDUE" in bureau.columns:
    overdue_records = (bureau["CREDIT_DAY_OVERDUE"] > 0).sum()

    print("Records with CREDIT_DAY_OVERDUE > 0:", overdue_records)
    print("Percentage:", f"{overdue_records / len(bureau) * 100:.2f}%")

Records with CREDIT_DAY_OVERDUE > 0: 4217
Percentage: 0.25%

In [33]:
#Active credit records
if "CREDIT_ACTIVE" in bureau.columns:
    active_records = (bureau["CREDIT_ACTIVE"] == "Active").sum()

    print("Active bureau credits:", active_records)
    print("Percentage:", f"{active_records / len(bureau) * 100:.2f}%")

Active bureau credits: 630607
Percentage: 36.74%

In [34]:
#Credit type per applicant
if "CREDIT_TYPE" in bureau.columns:
    credit_types_per_customer = bureau.groupby("SK_ID_CURR")["CREDIT_TYPE"].nunique()

    print("Distribution of number of different credit types per applicant:")
    display(credit_types_per_customer.value_counts().sort_index())

Distribution of number of different credit types per applicant:

CREDIT_TYPE
1    109315
2    166653
3     27652
4      2113
5        74
6         4
Name: count, dtype: int64

In [36]:
#Days info
days_cols = [col for col in [
    "DAYS_CREDIT", "DAYS_CREDIT_ENDDATE", "DAYS_ENDDATE_FACT", "DAYS_CREDIT_UPDATE"
] if col in bureau.columns]

print("Date-related columns:", days_cols)
display(bureau[days_cols].describe().T)

Date-related columns: ['DAYS_CREDIT', 'DAYS_CREDIT_ENDDATE', 'DAYS_ENDDATE_FACT', 'DAYS_CREDIT_UPDATE']

,count,mean,std,min,25%,50%,75%,max
DAYS_CREDIT,1716428.0,-1142.107685,795.164928,-2922.0,-1666.0,-987.0,-474.0,0.0
DAYS_CREDIT_ENDDATE,1610875.0,510.517362,4994.219837,-42060.0,-1138.0,-330.0,474.0,31199.0
DAYS_ENDDATE_FACT,1082775.0,-1017.437148,714.010626,-42023.0,-1489.0,-897.0,-425.0,0.0
DAYS_CREDIT_UPDATE,1716428.0,-593.748320,720.747312,-41947.0,-908.0,-395.0,-33.0,372.0

In [37]:
for col in days_cols:
    sentinel_count = (bureau[col] == 365243).sum()
    print(f"{col} - count of 365243: {sentinel_count}")

DAYS_CREDIT - count of 365243: 0
DAYS_CREDIT_ENDDATE - count of 365243: 0
DAYS_ENDDATE_FACT - count of 365243: 0
DAYS_CREDIT_UPDATE - count of 365243: 0

In [38]:
if "CNT_CREDIT_PROLONG" in bureau.columns:
    print("Credit prolongation statistics:")
    display(bureau["CNT_CREDIT_PROLONG"].describe())

Credit prolongation statistics:

count    1.716428e+06
mean     6.410406e-03
std      9.622391e-02
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      9.000000e+00
Name: CNT_CREDIT_PROLONG, dtype: float64

In [39]:
example_customer = credits_per_customer.idxmax()

print("Applicant with the most bureau records:", example_customer)
display(bureau[bureau["SK_ID_CURR"] == example_customer])

Applicant with the most bureau records: 120860

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
115133,120860,6800812,Closed,currency 1,-265,0,-260.0,-260.0,NaN,0,67500.0,0.0,NaN,0.0,Microloan,-248,NaN
182139,120860,6800826,Closed,currency 1,-178,0,-158.0,-158.0,NaN,0,67500.0,0.0,NaN,0.0,Microloan,-139,NaN
182140,120860,6800828,Closed,currency 1,-120,0,NaN,-76.0,NaN,0,36000.0,0.0,NaN,0.0,Microloan,-76,0.0
182141,120860,6800830,Closed,currency 1,-148,0,NaN,-76.0,NaN,0,36000.0,0.0,NaN,0.0,Microloan,-76,0.0
182142,120860,6800836,Closed,currency 1,-22,0,NaN,-11.0,NaN,0,36000.0,0.0,NaN,0.0,Microloan,-11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880937,120860,6800880,Closed,currency 1,-1338,0,NaN,-110.0,0.0,0,405000.0,0.0,0.0,0.0,Credit card,-105,NaN
880938,120860,6800881,Closed,currency 1,-1564,0,-1197.0,-1197.0,0.0,0,67500.0,NaN,NaN,0.0,Consumer credit,-1197,0.0
880939,120860,6800882,Closed,currency 1,-2127,0,-1820.0,-2004.0,0.0,0,39317.4,0.0,0.0,0.0,Consumer credit,-1983,NaN
880940,120860,6800883,Closed,currency 1,-1931,0,-1624.0,-1624.0,0.0,0,67991.4,0.0,0.0,0.0,Consumer credit,-1624,0.0
880941,120860,6800884,Closed,currency 1,-2771,0,-2467.0,-2467.0,0.0,0,70870.5,0.0,0.0,0.0,Consumer credit,-2467,0.0

In [40]:
print("========== BUREAU SUMMARY ==========")
print("Total bureau rows:", len(bureau))
print("Unique applicants:", bureau["SK_ID_CURR"].nunique())
print("Unique bureau credits:", bureau["SK_ID_BUREAU"].nunique())
print("Applicants without bureau history:", len(ids_without_bureau))
print("Numeric columns:", len(numeric_cols))
print("Categorical columns:", len(categorical_cols))

========== BUREAU SUMMARY ==========
Total bureau rows: 1716428
Unique applicants: 305811
Unique bureau credits: 1716428
Applicants without bureau history: 44020
Numeric columns: 14
Categorical columns: 3